baseURL: https://yutingwu-portfolio.netlify.app/
languageCode: en-us
title: Portfolio website for Yuting Wu
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      #Welcome to my website!
    title: Hi, my name is Yuting Wu.
  blog: {}
  contact:
    address:
      - city: London
        country: UK
        street: Regent's Park
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: ywu.mam2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (07) 925713306 
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Joanna Wuser
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      #- icon: fa-twitter
      #  label: Twitter
      #  url: https://www.twitter.com
      #- icon: fa-facebook
      #  label: Facebook
      #  url: https://www.facebook.com
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/_bound.ary_/
      - icon: fa-github
        label: GitHub
        url: https://github.com/YutingWu-Joanna
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/yuting-wu-joanna/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: lbssoc.jpg #换照片 到themes\forty、static、xxx ppt
        subtitle: A Coffee lover
        title: About me
        url: blogs/yutingwu #blog里面修改 slug
      - image: work.jpg
        subtitle: Details about my previous internships
        title: My resume
        url: blogs/myresume
      - image: director.jpg
        subtitle: GDP components over time and among countries
        title: Project1-GDP components
        url: blogs/gdp
      - image: bikes.jpg
        subtitle: Excess rentals in TfL bike sharing
        title: Project2-Bike rentals
        url: blogs/bike
      - image: conference.jpg
        subtitle: IBM HR Analytics Employee Attrition & Performance
        title: Project3-IBM HR Analytics
        url: blogs/ibm
      - image: vote.jpg
        subtitle: Applied Statistics Pre-programme assignment
        title: Pre-programme assignment
        url: blogs/preprogramme
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \r\n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \r\n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \r\n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\r\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Massa libero
    url: blogs
